### PR TITLE
Fix waiting for register updates

### PR DESCRIPTION
**Pull request by FliegenKLATSCH**

### CODE REVIEW

**Comment by FliegenKLATSCH** [comment]
@AgilatechSystems ?

**Comment by AgilatechSystems** [comment]
Sorry we dropped the ball on the request for so long. The improvements and bug fixes look okay.

**Comment by FliegenKLATSCH** [comment]
@AgilatechSystems Thanks. Not sure how this update mechanism works, but looks like you still have to publish it to npm somehow?

**Comment by FliegenKLATSCH** [comment]
@AgilatechSystems ping, would be nice if you could publish the latest version.

**Pull request merged**
